/*******************************************************************************
 * Copyright (c) 2024 Allied Vision Technologies GmbH
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *******************************************************************************/

#ifndef VISIONTRANSFER_EXTERNALBUFFERSET_H
#define VISIONTRANSFER_EXTERNALBUFFERSET_H

#include "visiontransfer/common.h"
#include "visiontransfer/imageset.h"
#include "visiontransfer/externalbuffer.h"

namespace visiontransfer {

/// A lockable ensemble of one or more disjoint ExternalBuffers. Each set will back the data for one ImageSet. (Functionality not available in Python API.)
class VT_EXPORT ExternalBufferSet {
public:
    /**
     * \brief Create an empty external buffer set that can be populated with
     *  an arbitrary number of buffers with indidivual role parts, acting as an
     *  ensemble during reception.
     *
     * \param handle A user-provided, *unique*, numeric handle for this buffer set.
     *  The default handle of 0 means 'unspecified, autogenerate a handle internally'.
     *  Caution: You should NOT mix user-provided and autogenerated handles in the same application!
     *
     * \param dedicatedImageType If set to non-default (ImageSet::IMAGE_UNDEFINED), that
     *  setting will be used to restrict the role of this buffer set to solely one channel.
     *  This is only relevant if the buffer pools for the different roles should
     *  operate independently, with all potential pitfalls.
     *  The recommended default setting results in a synchronized multi-part buffer set.
     *  It is essential that the buffer part mapping (see ExternalBuffer) is completely
     *  defined with respect to the intended use case.
     *  Multi-part and single-part buffer sets cannot be mixed at the same time in
     *  an AsyncTransfer / ImageTransfer.
     */
    ExternalBufferSet(ImageSet::ExternalBufferHandle handle = 0, ImageSet::ImageType imageType = ImageSet::IMAGE_UNDEFINED);
    ExternalBufferSet(const ExternalBufferSet& orig);
    const ExternalBufferSet& operator=(const ExternalBufferSet& from);
    ~ExternalBufferSet();

    /// Return the auto-generated unique buffer set handle
    ImageSet::ExternalBufferHandle getHandle() const;
    /// Add a single ExternalBuffer. At least one is required for an
    void addBuffer(ExternalBuffer buf);
    int getNumBuffers() const;
    ExternalBuffer getBuffer(int idx) const;
    /// Return 'ready for consumer' state, i.e., whether buffer set has been filled and taken out of the reception routine
    bool getBlockedByUser() const;
    /// Marks the buffer set 'ready' for the API consumer. (Used internally.)
    void setBlockedByUser(bool ready);
    /// Return the dedicated ImageType accepted by this buffer set; default IMAGE_UNDEFINED for a generic multipart buffer set
    ImageSet::ImageType getImageType() const;

private:
    // We follow the pimpl idiom
    class Pimpl;
    Pimpl* pimpl;
};

} // namespace

#endif


